openapi: 3.0.0
info:
  title: Auth Service - Login
  version: 1.0.0
paths:
  /login:
    post:
      summary: Authenticate and log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's registered email address
                password:
                  type: string
                  format: password
                  description: User's password
              example:
                email: user@example.com
                password: securePassword123
      responses:
        '200':
          description: User successfully logged in
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session_id=abcde12345; HttpOnly; Path=/; Max-Age=3600
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  userId:
                    type: string
                    format: uuid
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password
